### ISSUE TITLE
Disable all like/favorite related functionality

### ISSUE THREAD

**Issue by miladf** [refugeetech/MigHub#111]
Because of resource and time conditions we need to cut this off for the release so please:
- Comment out the "these are the apps you liked so far" on the "Main view" (see below)
  ![footer](https://cloud.githubusercontent.com/assets/1964180/18140687/e1ac28f4-6fb6-11e6-958d-67653e68de2f.png)
- Comment out the "heart" on the "Category view" below each description of 

![image](https://cloud.githubusercontent.com/assets/1964180/18140782/479b41e0-6fb7-11e6-9edb-ad05bffcafe5.png)
- Comment out the "heart" in the upper right on the "Project view" and the text about number of likes
  ![articlepage media](https://cloud.githubusercontent.com/assets/1964180/18140670/d608638c-6fb6-11e6-8f4d-7a7819da970e.png)

**Comment by adelablue** [comment]
fixed.
