### ISSUE TITLE
CSS styling for "About us" page

### ISSUE THREAD

**Issue by miladf** [refugeetech/MigHub#112]
- Paragraph text 14pt
- Headline text 24pt
- List text (the contributors) 14pt
- Comment out the first "Follow us", "Facebook", "Twitter" and "Linkedin"
- Center Refugee Tehc logo
- Link "Visit us" to http://refugeetech.com/
- Add a "Facebook" link between "visit us" and "add your app in Setelin" and link to https://www.facebook.com/refugeetech/
- Link "add your app in Setelin" to https://refugee1.typeform.com/to/
- Add email-to: info@refugeetech.com on "contact"

![setelinabout 1](https://cloud.githubusercontent.com/assets/1964180/18141379/8f9d45e0-6fb9-11e6-90bb-e559c1fe16de.png)

vs. 

![14163941_10154583856899388_1262623138_o](https://cloud.githubusercontent.com/assets/1964180/18141192/d3a2f394-6fb8-11e6-9c21-0be5d1e1798a.jpg)

**Comment by adelablue** [comment]
fixed and I removed the feedback link for now, since it's not working.
