### ISSUE TITLE
Adding intiatives and assets that doesn't show (CMS not working so we need to do it manually in the database)

### ISSUE THREAD

**Issue by miladf** [refugeetech/MigHub#116]
We need to put some initiatives and some assets (logos, descriptions etc.) on Setel.in through manually putting it in the database (yes, I know, retarded but the CMS we built is not working properly)

@elhabib will put all stuff that needs to be done here

**Comment by ghost** [comment]
- Healthcare category and Media and Telecommunication show nothing. They should show some. 
- Logos for several initiatives do not show. May be need to be added manually somewhere (i have not read any code, or so what you use to develop)

**Comment by ghost** [comment]
Healthcare must show clinicfinder and vårdguiden.
Media and communication has to show at least migtalks, the local voices, i am not a refugee.
- Logos are missing for, welcome talents, lingio x2, invitationdepartment, spårkraft, integrationsakedemin.

**Comment by ghost** [comment]
welcome talents: http://www.freeiconspng.com/uploads/linkedin-logo-3.png
lingio x2: https://drive.google.com/file/d/0B3LVOhWM53KdTjdzd1IwXzItY3M/view
invitationdepartment: https://www.flickr.com/photos/unitedinvitations/20899884938/
spårkraft: https://pbs.twimg.com/profile_images/704320425598312448/qqaO0y1W.jpg
integrationsakedemin: https://media.licdn.com/media/AAEAAQAAAAAAAAhZAAAAJGJmZTI2NWYzLTlkNTgtNDk1YS1hZWM4LTQ1NzMyNzgwMTA2Mg.png

**Comment by miladf** [comment]
@superyass could you fix the logos? I will send you the descriptions of "clinic finder", "vårdguiden", "MigTalks", "The local voices" and "I am not refugee later" tonight

**Comment by superyass** [comment]
Ok, got it.

**Comment by miladf** [comment]
Initiative name: 
**ClinicFinder**
Category: 
_Healthcare_
Webpage link:
_http://www.clinicfinder.org/_
Logo link:
_https://www.dropbox.com/s/1zkam41vuu1t0g1/Doctors%20of%20the%20world%20logo%20transparent%20.tif?dl=0_
Short description: 
_ClinicFinder helps refugees find the nearest health clinic_
Detailed description: 
_The ClinicFinder is a mobile web-app, provided by Doctors of the World UK, designed to provide simple and clear information about free primary healthcare and medical services for refugees and migrants across Europe. It uses your phone’s GPS location to show on a map the nearest free health clinics and what services can be accessed. It also allows you search by location (e.g. Berlin, Athens) and by specific service required (e.g. Children, Survivor of Violence), while language options currently include English, Arabic, Farsi and French. ClinicFinder also allows anyone to add the locations of other eligible clinics (verified by Doctors of the World UK) and we encourage users, health professionals and other organisations to show their friends, patients and spread the word!_

**Comment by miladf** [comment]
Initiative name: 
**MIG Talks**
Category: 
_Communication and Media_
Webpage link:
_http://www.migtalks.se/_
Logo link:
_https://scontent-arn2-1.xx.fbcdn.net/v/t1.0-9/10570291_846698012124467_1960427551368881929_n.jpg?oh=1346d3e2bfcdd6a7be6f18cd08ac4104&oe=588359C0_
Short description: 
_MIG Talks raises the voices of the humans behind the migrations statistics._
Detailed description: 
_MIG Talks is a Communication Initiative that aims to spread knowledge about migration to Sweden. It provides a platform for the exchange of information, experiences and perspectives between newcomers and societal actors in Sweden. The goal is to contribute to a nuanced and inclusive public conversation.._

**Comment by miladf** [comment]
Initiative name: 
**The Local Voices**
Category: 
_Communication and Media_
Webpage link:
_http://www.thelocal.se/voices/_
Logo link:
_http://www.thelocal.se/assets/voices/image/the-local-voices-logo.png_
Short description: 
_The Local Voices lets newcomers tell their stories and share their views._
Detailed description: 
_The Local Voices gives a voice to newcomers in Sweden by publishing news and stories in English for and about newly-arrived refugees and asylum seekers in Sweden. The site serves as an online platform for members of this community to learn about Sweden and share their stories with other newcomers, Swedes, and the wider world._

**Comment by miladf** [comment]
@elhabib please do the same with "Vårdguiden" (doesn't exist in the typeform) and "I'm not a refugee" (has too much text in short description and is according to the one who applied under 'employment' rather than 'media and communication' as you mention)

**Comment by miladf** [comment]
@elhabib please also give us a better description for "integrationsakademin" they didn't provide us info in the right format, should we have them in it?

**Comment by ghost** [comment]
the description of department akademin
"Through our sessions and courses, we help people understand the changing modern Swedish society. We motivate, enhances self-esteems, treating fears and reinforce social skills for individuals. We help our future innovators, leaders, engineers, developers, sellers, builders, teachers, etc. to realise their goals and dreams in their society. We encourage volunteers to help and coach our participants.  We also help companies and businesses to take advantage of the diversity and become more open to welcome new cultures, perspectives and ways of thinking.  We cooperate with other organisations, initiatives and intuitions. We believe that an organisation can grow even more and become stronger if they collaborate with each other and find players that complement themselves."

**Comment by ghost** [comment]
@miladf @superyass  vårguiden is in the project hub, it should be taken from there. But this whole thing is wrong. We can not do this manually all the time. There is a bug somewhere (maybe with the CMS) that makes it that "healthcare" and "Media and Communication" initiaves do not appear in setelin. That is what needs fixing. Not adding this manually all the time. So please fix that bug. My guess would be that someone mistyped an Id while coding. so I d check that first!

**Comment by miladf** [comment]
@elhabib we have already noticed that media & communication is written "media_and_communication", "media_communication" and "media_and_comunication"...........................

**Comment by ghost** [comment]
excatly what i thought. The same with healthcare, then, @superyass  check if it works localy when you change that. I can only see the commited version on my side.

**Comment by superyass** [comment]
the problem is there is no 'delete' functionality...so we have to add it in the backend

**Comment by ghost** [comment]
you can add new ones, and hide those we do not want by unchecking the box 'has this initivative filled the requirement to be in setelin
'

**Comment by superyass** [comment]
i fixed media_and_communication ...i'll fix healthcare then i'll push...

**Comment by ghost** [comment]
you can add new ones, and hide those we do not want by unchecking the box 'has this initivative filled the requirement to be in setelin.

**Comment by superyass** [comment]
these image links are not working : 
400contacts: https://pbs.twimg.com/profile_images/658954410320613376/lfmxz3ck_400x400.png
Vårdguiden : http://www.1177.se/style/636003023283217187/img/base/1177-sociallogo-100x100.png

**Comment by miladf** [comment]
Vårdguiden: http://www.1177.se/style/636081493720272265/img/base/1177-sociallogo-100x100.png
400contacts: http://a2.mzstatic.com/us/r30/Purple60/v4/59/5d/07/595d07f7-cdfc-1bf4-0ad0-b41db1136137/icon175x175.jpeg

**Comment by miladf** [comment]
@superyass 
Website for **Welcomeapp** missing: http://welcomeapp.se/
Website for **Integrationsakademin** missing: http://integrationsakademin.se/
iOS link **Sellay** missing: https://itunes.apple.com/tr/app/sellay-english-speaking-easy/id1095067669?mt=8 
Android link **Sellay** missing: https://play.google.com/store/apps/details?id=se.ademes.sellay225583&hl=sv

Website for **Welcome Talent** missing: http://www.welcometalent.se/
Website for **Novare Potential** missing: http://www.novarepotential.com/
Comment out **Competency** for now.
Website for **Incluso** missing: http://www.incluso.se/en/

Logo for **Lingio Language Learning** missing: https://drive.google.com/file/d/0B3LVOhWM53Kddmt3d0NRY2l1anM/view
Logo for **Lingio Translate** missing: https://drive.google.com/file/d/0B3LVOhWM53KdTjdzd1IwXzItY3M/view

Website for **The Local Voices** missing: http://www.thelocal.se/voices

Website for **refugees-welcome.se** missing: http://refugees-welcome.se/?lang=en

Logo for **Clinic Finder** missing: https://www.dropbox.com/s/1zkam41vuu1t0g1/Doctors%20of%20the%20world%20logo%20transparent%20.tif?dl=0 (if that doesn't work use this: 
![screen shot 2016-09-04 at 16 16 56](https://cloud.githubusercontent.com/assets/1964180/18231483/15700a82-72bb-11e6-9e4a-09fbdbfa2eb0.png) )

Website for **Vårdguiden** missing: http://www.1177.se/Other-languages/Engelska/

**Comment by miladf** [comment]
bro can u add these now? @superyass

**Comment by superyass** [comment]
Ok.

**Comment by superyass** [comment]
for the Lingio logos, we need them to be hosted somewhere...not on the cloud drives
same thing for Clinic Finder

**Comment by miladf** [comment]
Clinic finder: https://doctorsoftheworld.org/wp-content/themes/bota/assets/images/logo-small.png

**Comment by miladf** [comment]
Vårdguiden: http://www.1177.se/style/636081493720272265/img/base/1177-sociallogo-100x100.png

**Comment by miladf** [comment]
Lingio Language Learning: https://dev.setel.in/img/apps/Lingio-Language-Learning-logo.png
Lingio Translate Logo: https://dev.setel.in/img/apps/Lingio-Translate-logo.png

**Comment by miladf** [comment]
(but use the route and not the whole URL, that is get rid of dev.stel.in/ and only use "/img...."

**Comment by miladf** [comment]
Please update the info in this intiative (it already exist but doesn't have description etc.)

Initiative name: 
**Just Arrived**
Category: 
_Employment_
Webpage link:
_http://justarrived.se/_
Short description: 
_We give new arrivals a chance to enter the Swedish labor market._
Detailed description: 
_Just Arrived is a digital service that matches newly arrived to simple jobs with the purpose to help them build their resumé and credentials in Sweden. A company posts a job, selects a candidate, rates the candidate's work once completed and automatically gets an invoice. The candidate creates a profile, gets offers, completes the job, rates the company and gets salary paid to an account of his/her choice. We take care of all the administration and insurances for both sides. The app is in 8 languages and for messaging, Google Translate translates automatically._

**Comment by miladf** [comment]
Hahah the longest comment ever, I guess github wasn't built working this way but who cares when time is limited.... Very good job man @superyass

**Comment by superyass** [comment]
thanks bro
