### ISSUE TITLE
Swipe between categories 

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#12]
When in a single category view, this feature will allow the user to swipe to see the next/previous category.

**Comment by miladf** [comment]
So you go from here: https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryA_DT02.png

to for instance here through swiping horizontally:
https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryB_DT01.png

**Comment by leosa83** [comment]
closed by #20
