### ISSUE TITLE
Background for "media-and-communication" and "healthcare" doesn't show after the variable changes

### ISSUE THREAD

**Issue by miladf** [refugeetech/MigHub#138]
![14194194_10154597325634388_279610526_n](https://cloud.githubusercontent.com/assets/1964180/18231815/084a576a-72c3-11e6-8701-b8231c43e2b1.jpg)
![14218452_10154597325674388_50726507_n](https://cloud.githubusercontent.com/assets/1964180/18231817/0d1c1878-72c3-11e6-8c18-eb917b1a12af.jpg)

vs. 

![category- healthcare](https://cloud.githubusercontent.com/assets/1964180/18231826/30100420-72c3-11e6-9a61-0aa5e1e08e4f.png)
![category- mediacommunication](https://cloud.githubusercontent.com/assets/1964180/18231827/352fb6bc-72c3-11e6-944e-ebea4199333d.png)

**Comment by miladf** [comment]
Assets: https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AABof5dvR2SJuhAjpUymlV0Ma/BackgroundImages?dl=0

But I think all assets are up there, its just that we changed the name that makes it not retrieve the picture and use it as a background.

**Comment by superyass** [comment]
yes they are i'll fix them, but the translations.js file should be updated
