### ISSUE TITLE
App link tags in app list 

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#14]
In the single category view by the app name and icon load tags after the available links. Possible tags are Web, iOS, Android

**Comment by miladf** [comment]
Image on how this looks like in the interface (the blue tags below the like-button): https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryListDT02.png

**Comment by adelablue** [comment]
Since I didn't find the previous mockup, I checked the current mockup, and feel we don't need to "App link tags in app list #14", although I already fetched data.

**Comment by leosa83** [comment]
@adelablue You are right and i am therefore closing this issue as it is not a required feature anymore.
