### ISSUE TITLE
Change the variable on locale app so its "media-and-communication"

### ISSUE THREAD

**Issue by miladf** [refugeetech/MigHub#145]
Translations are not retrieved from localeapp now as it is different variable names, please change to "media-and-communication" on locale and check if it works :)

**Comment by miladf** [comment]
nvm I did it

**Comment by miladf** [comment]
Seems like I didn't manage to fix the problem. Please check.

**Comment by Ozcino** [comment]
This is working on dev

**Comment by ghost** [comment]
I did this long ago ...
