### ISSUE TITLE
Number of likes in Category view 

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#15]
Add in the number of likes an app has next to the icon. This will be done in Category.html in the list of apps

**Comment by miladf** [comment]
Like in the interface below (right mister @Ozcino ?):
https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryListDT02.png

**Comment by Ozcino** [comment]
Right! The fifth image

**Comment by leosa83** [comment]
close by #22 ! Thanks!
