### ISSUE TITLE
Fill screen on scroll

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#16]
The list of apps loads as a card with margin on the sides. When the top of the card hits the top of the screen the margin should animate out and the white background should fill the screen.

**Comment by miladf** [comment]
From this:
https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryA_DT02.png

to this:
https://www.dropbox.com/sh/sdluuq4qduqztag/AAAEOm2wNFDAjjdEzfb5T2B6a/02Categories%2BList?dl=0&preview=CategoryListDT02.png

**Comment by leosa83** [comment]
closed by #20
