### ISSUE TITLE
Aminate category circle to grow and "become" the single category view

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#17]
The idea is for the category circle to grown and fill the screen and "become" the category views background. Later the app list should animate in from below. The cirkle should grow as to give the user a feel of "going into" the circle, kinda like the small cicle being a window.

**Comment by leosa83** [comment]
@Ozcino notice the low prio tag on this one. Am not sure if it exists as a req on the new design.

**Comment by leosa83** [comment]
Onhold to be evaluated for the next iteration
