### ISSUE TITLE
Resize app.html .ion-modal-view in web layout 

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#2]
The app.html information modal ( .ion-modal-view ) is too small in the web layout, the modal needs to present the info better.  Either:
- wider and devided into two collapsable collumns 
  or
- a longer modal

**Comment by leosa83** [comment]
@Ozcino Can you give more details on this issue as its quite diffuclt to know exactly what you mean. Thanks!

**Comment by leosa83** [comment]
Will close this issue until we have some more info why its necessary.
