### ISSUE TITLE
Detailed Project View

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#23]
When clicking  a project it should look like the following:

![articlepage final](https://cloud.githubusercontent.com/assets/14599430/16902264/a4cb62d0-4c5a-11e6-93c7-217ef2e45a2f.png)
- The give feedback button redirects to a typeform where the user can give feedback on the app.
- The logic of the "Get it"/"Visit us" button is: (stupid pseudo code)

```
if current device is ios and appstore link exists then "Get it" else
if current device is android and google play link exists then "Get it" else
if homepage link exists then "Visit us" else if facebook link exists then "Visit us"
```

**Comment by leosa83** [comment]
@adelablue The bottom part are project pics just like in the appstore which u can swipe.

**Comment by leosa83** [comment]
@adelablue Appearently that was the old pic - will upload the new one later.

**Comment by adelablue** [comment]
Wonder if Oskar will take this? I found another ionic related bug, I will log it and try to fix.

**Comment by leosa83** [comment]
@Ozcino are you working on this? :)

**Comment by Davito163** [comment]
Is it possible to change the layout of the article page? This way we don't need a background picture for every app and it will be easier to maintain. 
![articlepage media](https://cloud.githubusercontent.com/assets/14599430/16902264/a4cb62d0-4c5a-11e6-93c7-217ef2e45a2f.png)

**Comment by leosa83** [comment]
@Davito163 Absolutely. Sorry for the late reply!

**Comment by leosa83** [comment]
@Ozcino Are you working on this or should i start?

**Comment by leosa83** [comment]
If we are to implement the "Gallery" we will need to expand the schema a bit.

**Comment by leosa83** [comment]
develop was merged into detail-app branch developing this feature on commit :2ca4184e2d02259d22b00a65fb1eb9ca1fe5f89a
