### ISSUE TITLE
Icon size in category

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#3]
# Description

The Icon loading for the individual category view is way to big in a full width browser and needs to be tamed
# TODO
- [ ] Load icons based on the viewport size

**Comment by stenehall** [comment]
This would be my suggested size: https://www.dropbox.com/s/sygd7nz4ng5h5s2/Screenshot%202016-06-12%2012.57.51.png?dl=0

It's using up to 100% of the viewport but never bigger than 300px. On smaller screens it's nice to use 100% imho.
