### ISSUE TITLE
Feature /categories (MainMenu) view

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#38]
# Description

The MainMenu view should look like this:
![_mainmenu- media education info employment housing language health social](https://cloud.githubusercontent.com/assets/710548/17335789/96df9fb4-58db-11e6-82ce-eaca4d93d552.png)
# Color Codes for background Icons for each category

Education: #4e6ba4 
Media & Com: #a6404b 
Information: #488674 
employment: #af9034 
Housing: #9e5e81 
Language: #ae5540 
healthcare: #ad4550 
Social: #4765a0

**Comment by leosa83** [comment]
This is not ready yet as we are waiting for the assets from @Davito163

**Comment by leosa83** [comment]
What is need still is setting the category svgs in the background, make sure it works for all browsers.

**Comment by leosa83** [comment]
The only thing needed now is to place the pictures so it looks good after having converted them to png.

**Comment by miladf** [comment]
@leosa83 do you guys need any assets or do you have everything? The colors are different, placement of icon and the alignment of the text compared to the picture above..

**Comment by irony** [comment]
I can have a look

**Comment by miladf** [comment]
@irony :heart:

**Comment by irony** [comment]
<img width="918" alt="screen shot 2016-08-24 at 00 05 58" src="https://cloud.githubusercontent.com/assets/395843/17911590/946b7d3e-698e-11e6-9f5f-d5c61952e523.png">
Should we use black as in the screenshot above, or white as in the brand book?

**Comment by miladf** [comment]
@irony the "Swedish" one would be nice? Otherwise the black one I think.

**Comment by irony** [comment]
sorry, I mean the color combinations in the categories menu. Should we use black text (as in the screenshot) or white text (as in the brand guidelines)?

also, do we have the Siri font?

**Comment by miladf** [comment]
Black text looks better on the background that we have on the categories (they are quite light). The brand guidelines shows white text on black background, so I think there is no problem (as David followed when doing the UI). Lets do it and check with David and Vitaly about it when its implemented 

I don't have the font, I just asked Vitaly about it in our slack channel.

**Comment by leosa83** [comment]
Updated the description with the colorcodes to be used for each category icon

**Comment by leosa83** [comment]
We are working on getting all the assets published here

**Comment by leosa83** [comment]
You can find the font here: https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AAC6OUchclVrD1-zyVEF2bHXa/Font?dl=0

**Comment by leosa83** [comment]
This is how it should look like, it was quite late yesterday so I forgot that this is the right version:
![mainmenu- media education info employment housing language health social copy 3](https://cloud.githubusercontent.com/assets/710548/17927980/b21c7b70-69f8-11e6-9019-d5bee9218c16.png)

**Comment by irony** [comment]
The font is now implemented, looks amazing

**Comment by leosa83** [comment]
Great! It sure does :)

**Comment by leosa83** [comment]
To make it actually look like in the design requires som good css skills. Anyone willing to really take this on?

**Comment by miladf** [comment]
@superyass Check this out.

**Comment by superyass** [comment]
Fixed with #97
