### ISSUE TITLE
App links

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#5]
# Description

None of the apps have links loaded to the buttons in the individual app view, they will need to be identified as Android/iOS/Web and apropriet buttons generated.
## Solution

The projects links have a "type" field:
- googlePlay => Google Play (android)
- appStore => Itunes App Store
- and so on
# Info

These are all the options in the schema definition for link types: 
['home','pic','mainPic','logo','web', 'article','blog','facebook', 'twitter', 'instagram', 'blogger','linkedin','other','appStore','googlePlay','windowsStore','github','slack','trello']

Check out the full ProjectsSchema definition in this file:
[ProjectSchema](https://github.com/refugeetech/platform/blob/develop/projects/collections/schema.js)

**Comment by irony** [comment]
I've added a basic implementation of this now. right now it only takes the link and tries to set an icon based on the type.

**Comment by leosa83** [comment]
closed by #20
