### ISSUE TITLE
About and Attribution Page

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#52]
# Description

The about page should look someting like this:

Where all who have contributed to the project should be listed

![about](https://cloud.githubusercontent.com/assets/710548/17649562/c3bdb5fa-6238-11e6-8bf6-510c7c2e0cb0.png)

**Comment by leosa83** [comment]
@Shahin89
Are you able to create a list of all who have contributed ?

**Comment by leosa83** [comment]
@Shahin89 
We also need a description of Refugee Tech

**Comment by leosa83** [comment]
A feedback typeform should be created for this page

**Comment by miladf** [comment]
@leosa83 this is needed. I can tell Shahin to get the copy for this by end of the week.

**Comment by miladf** [comment]
But this could be implemented asap.

**Comment by leosa83** [comment]
Yes it could

**Comment by leosa83** [comment]
@miladf You are assigned until the copy is ready after which u can hand it over to @superyass

**Comment by miladf** [comment]
@leosa83 Yes, but the let @superyass use dummy text for now.

**Comment by leosa83** [comment]
Sure but there are many other issues more prioritized so there will be no need to begin until the content is done.

Skickat från min iPhone

**Comment by miladf** [comment]
Well, then we can agree that he don't need to wait for the content if he finishes the other issues that are more prioritised.

**Comment by miladf** [comment]
@Davito163 is working on this right now.

**Comment by miladf** [comment]
![setelinabout](https://cloud.githubusercontent.com/assets/1964180/18038346/3551be64-6d97-11e6-9031-42f964242929.png)

**Comment by miladf** [comment]
Note that we haven't listed every person that has contributed yet and that the description of work is just dummy.

**Comment by Ozcino** [comment]
Started on this in local branch yesterday. will pick up when the rest of the copy is in.
