### ISSUE TITLE
Styling of detailed project view tags

### ISSUE THREAD

**Issue by Ozcino** [refugeetech/MigHub#53]
Style the detailed project view tags according to design view. 

<img src="https://cloud.githubusercontent.com/assets/14599430/16902264/a4cb62d0-4c5a-11e6-93c7-217ef2e45a2f.png"/>

**Comment by leosa83** [comment]
@Ozcino There is now a mainCategory field and some other updates. Will you be able to complete this issue?

There has been som majro changes to the develop branch so it might be easier to start branch off from develop anew and use your additions from the current branch.
