### ISSUE TITLE
Comment out the "Likes" element in the detailed app view

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#60]
# Description

We will not be implementing the likes feature yet. Therefore it needs to be hidden.
# Todo
- comment out: `<p class="likes"> {{ app.upvotes }} Likes </p>`  in the app.html template file

**Comment by irony** [comment]
Should we add a like button from Facebook instead?

**Comment by leosa83** [comment]
@irony Yes that would be preferable , but i rather see a Googleplus twitter pinterest etc aswell. There should exist som library to make this straightforward....

**Comment by leosa83** [comment]
@irony What do you think of this ? 
https://github.com/cornflourblue/angulike

**Comment by leosa83** [comment]
The FB like button will be implemeted instead
