### ISSUE TITLE
Mobile browsers not working on iOS

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#65]
# Description

On iOS:

On the develop branch
  Safari: blank page
  Chrome: blank page

On the grid-layout branch: https://github.com/refugeetech/MigHub/tree/feature/grid-layout
  Safari: Choosing an rtl language creates bugs , the page dissapears
  Chrome: Same thing
# Todo
- Debug the translate plugin

**Comment by superyass** [comment]
the problem is due the es6 support in safari which is not fully compatible yet

**Comment by leosa83** [comment]
closed by #68
