### ISSUE TITLE
Images not showing on Safari and Firefox

### ISSUE THREAD

**Issue by superyass** [refugeetech/MigHub#67]
## working branch :

feature/grid-layout branch

the projects icons on the main screen, are not showing!

**Comment by leosa83** [comment]
Thanks and Nice solution @superyass.

Testing reveals though it messes with the user interactions on mobile while swiping. So we need to ty something different. even if the images are now showing properly. thanks

**Comment by superyass** [comment]
i suggest converting the svg images to png with a width of 500px

**Comment by leosa83** [comment]
Now it works good with png images. we only need to make it look better in categories view.

**Comment by leosa83** [comment]
closes by #68
