### ISSUE TITLE
Improve Arabic translations

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#71]
# Descriptions

We are currently using google translated strings. Someone fluent in Arabic should translate.
# Todo
- Improve the following (except for the category descriptions until they are done in #50 )
-  When #50 is closes translate the category descriptions aswell

``````
$translateProvider.translations("ar", {
  "categories": "الفئات",
  "choose_language": "إختر اللغة",
  "education_description": "  الحصول على أكثر ذكاء، و تبدأ في النمو",
  "education_title": "التعليم",
  "employment_description": "ابدأ الشبكات ، والحصول على التدريب أو العمل",
  "employment_title": "الشغل",
  "health_description": "  جسمك هو المعبد الخاص بك ، دعنا صحي",
  "health_title": "  الصحة",
  "housing_description": " تريد وجود سقف فوق رأسك ؟ ",
  "housing_title": "السكن",
  "information_description": " تعلم المزيد عن عاداتنا و لماذا نحن نحب أن فايكا ",
  "information_title": "معلومات",
  "learnMore":"أعرف أكثر",
  "interface_direction": "rtl",
  "label": "اللغة العربية",
  "language_description": "  مرحبا ، كيف حالك ؟ ",
  "language_title": "لغات",
  "media_comunication_description": " قراءة قصص مذهلة ",
  "media_comunication_title": " وسائل الإعلام و المواصلات",
  "refugee_tech_info": " نهج حصلت على أي أفكار التطبيق المباشر لهم RT إذا المطور يريد تحميل التطبيق . ",
  "setelin_description": " حول setelin ، لوقا، و انهم عائدون في أسرع بكثير هذه المرة . أنا لا يمكن أن تعقد لهم! Artoo ، ومحاولة زيادة القوة ! عجلوا ، لوقا ! انتظر! أنا على الزعيم. تشبث ، Artoo ! استخدم القوه يا لوك. ترك، لوقا . مشاركة أو زيارة ؟ ",
  "setelin_footer": "  حول setelin ، لوقا، و انهم عائدون في أسرع بكثير هذه المرة . أنا لا يمكن أن تعقد لهم! Artoo ، ومحاولة زيادة القوة ! عجلوا ، لوقا ! انتظر! أنا على الزعيم. تشبث ، Artoo ! استخدم القوه يا لوك. ترك، لوقا . مشاركة أو زيارة ؟   ",
  "setelin_header": " جلة من امرنا، لوقا ، انهم يأتون في أسرع بكثير هذه المرة . أنا لا يمكن أن تعقد لهم! Artoo ، ",
  "social_description": " الخروج من هناك و الحصول على بعض الأصدقاء",
  "social_title": "تواصل اجتماعي"
});```
``````

**Comment by ghost** [comment]
I am on this.

**Comment by miladf** [comment]
@elhabib lets do it after we have all english copy in place. That is after we meet in 1.5h 😄

**Comment by miladf** [comment]
@elhabib plz send this to mister Yassinho

**Comment by ghost** [comment]
Better arabic translation:

$translateProvider.translations("ar", {
  "categories": "فئات",
  "choose_language": "إختر اللغة",
  "education_description": "  قم بتطوير خبراتك المعرفية و تنمية مهاراتك من اجل مستقبل أفضل",
  "education_title": "تعليم",
  "employment_description": "ابحث عن  فرص شغل او تكوين مهني، التق بمهنيين بنفس اهتماماتك",
  "employment_title": "شغل",
  "health_description": "العقل السليم في الجسم السليم، صحتك امانة عليك",
  "health_title": "  صحة",
  "housing_description": " المنزل في الغربة وطن. إبحث عن بيتك في السويد ",
  "housing_title": "سكن", 
  "information_description": " تعرف على العادات، التقاليد و القوانين السويدية و أكثر من ذلك",
  "information_title": "معلومات",
  "learnMore":"أعرف أكثر",
  "interface_direction": "rtl",
  "label": "العربية",
  "language_description": "  مرحبا! تعلّم لغات جديدة بأساليب متطورة و سهلة. ",
  "language_title": "لغات",
  "media_comunication_description": " تّعرف على قصص ملهمة، و تجارب مثيرة غيرت حياة الناس",
  "media_comunication_title": " إعلام و مواصلات",
  "refugee_tech_info": " نقوم بتوحيد جهود المجتمع، من اجل مساعدة القادمين الجدد. نقوم بذلك من خلال توظيف تكنولجيات وخدم معدة لذلك ",
  "setelin_description": " تم إنشاء 'ستل إن' خلال هكاتون نظمته 'ريفوجي تك ' مع مصلحة الهجرة و 'ستكهولم تك '. خلال الهكاتون، تم توحيد جهود المبادرات التي تساعد اللاجئين في السويد من خلال إنشاء هذا التطبيق.
قامت 'ريفوجي تك ' بالسهر على اتمام التطبيق ",
  "setelin_footer": "    ",
  "setelin_header": " ",
  "social_description": " قل لي من تعاشر، أقول لك من أنت. تعرف على أناس جدد و ابدأ صداقات جديدة",
  "social_title": "تواصل اجتماعي"
});```

**Comment by ghost** [comment]
English is here:

$translateProvider.translations("en", {
  "categories": "Categories",
  "choose_language": "Change Language",
  "education_description": "  Get smarter, develop new skills and continue growing",
  "education_title": "Education",
  "employment_description": "Start networking, get an internship, a job or start new business",
  "employment_title": "Employment",
  "health_description": "Your body is your temple. Find the care you need to stay healthy.",
  "health_title": "  Healthcare",
  "housing_description": "Get a home in your new homeland.",
  "housing_title": "Accommodation", 
  "information_description": " Learn all about Sweden and Swedes, from Bureaucracy to Fikas",
  "information_title": "Information",
  "learnMore":"Learn More",
  "interface_direction": "rtl",
  "label": "English",
  "language_description": " Hej! Hola? Here are fun ways to learn new languages ",
  "language_title": "Language",
  "media_comunication_description": "Get inspired and learn from other people’s lives and experiences",
  "media_comunication_title":"Media and Communication",
  "refugee_tech_info": " We build bridges between parts of the society to enable newcomers potential relying on efficiently designed and developed solutions",
  "setelin_description": " Setelin was created as a result of a hackathon that was organised by Refugee Tech, together with Migrationsverket and STHLM TECH. The hackathon joined forces of Swedish tech initiatives who deal with social topics.
Refugee Tech has taken the burden of the development of  the Setelin platform, together with the help of several volunteers and contributors.",
  "social_description": " Friends make us who we are, find new friends and meet new folks",
  "social_title": "Social"
});```

**Comment by ghost** [comment]
@adelablue check the copy in the previous comments, both, arabic and english

**Comment by ghost** [comment]
Farsi

$translateProvider.translations("fa", {
  "categories": "دسته بندی ها",
  "choose_language": "انتخاب زبان",
  "education_description": "  باهوش تر شوید و مهارت هایتان  را بیافزایید",
  "education_title": "تحصیلات",
  "employment_description": "با دیگران ارتباط برقرار کنید،تا کارآموزی ويا شغل ثابت  بگیرید",
  "employment_title": "استخدام",
  "health_description": "عقل سالم در بدن سالم،  باید ازش مراقبت کرد",
  "health_title": "سلامت",
  "housing_description": "خانه ای برای زیستن در کشور جدیدتان بیابید",
  "housing_title": "مسکن", 
  "information_description": "با آداب و رسوم و قوانین سوئد بیشتر آشنا شوید",
  "information_title": "اطلاعات",
  "learnMore":"بیشتربدانید",
  "interface_direction": "rtl",
  "label": "فارسی",
  "language_description": "سلام! روش های جالب برای آموختن زبان جدید",
  "language_title": "زبان",
  "media_comunication_description": "از زندگی وتجربیات دیگران الهام بگیرید",
  "media_comunication_title": "رسانه و ارتباطات",
  "refugee_tech_info": " نهج حصلت على أي أفكار التطبيق المباشر لهم RT إذا المطور يريد تحميل التطبيق . ",
  "setelin_description": " ستلین در یک هکتن با مدیریت رفیوجی تک و همکاری اداره ی مهاجرت و استکهلم تک شکل گرفت. این محفل پروژه هایی که هدف کمک کردن به مسائل اجتماعی دارند را دور هم جمع کرد.
رفیوجی تک مسؤلیت توسعه وتکمیل کردن پلتفرم ستلین را ، با یاری داوطلبان و همکاران دیگر،  به عهده گرفت.
",
  "setelin_footer": "  حول setelin ، لوقا، و انهم عائدون في أسرع بكثير هذه المرة . أنا لا يمكن أن تعقد لهم! Artoo ، ومحاولة زيادة القوة ! عجلوا ، لوقا ! انتظر! أنا على الزعيم. تشبث ، Artoo ! استخدم القوه يا لوك. ترك، لوقا . مشاركة أو زيارة ؟   ",
  "setelin_header": " جلة من امرنا، لوقا ، انهم يأتون في أسرع بكثير هذه المرة . أنا لا يمكن أن تعقد لهم! Artoo ، ",
  "social_description": "دوستان جدید بیابید و با مردمان جدید آشنا شوید",
  "social_title": "اجتماعي"
});```

**Comment by adelablue** [comment]
got it!

**Comment by miladf** [comment]
$translateProvider.translations("sv", {
  "categories": "Kategorier",
  "choose_language": "Språk",
  "education_description": "Bli mer skicklig, utveckla nya kompetenser och fortsätt växa",
  "education_title": "Utbildning",
  "employment_description": "Börja nätverka, få ett internship, ett jobb eller starta eget företag",
  "employment_title": "Jobb",
  "health_description": "Din kropp är ditt tempel. Hitta den vård du behöver för att hålla dig frisk",
  "health_title": "  Hälsa",
  "housing_description": "Få ett boende i ditt nya hemland.",
  "housing_title": "Boende", 
  "information_description": “Lär dig allt om Sverige och svenskar, allt från byråkrati till fika",
  "information_title": "Information",
  "learnMore":"Learn More",
  "interface_direction": "rtl",
  "label": "Svenska",
  "language_description": “Hello! Hola! Här har du några roliga sätt att lära dig nya språk",
  "language_title": "Språk",
  "media_comunication_description": "Bli inspirerad och ta lärdom från andra människors liv och erfarenheter",
  "media_comunication_title":"Media och Kommunikation",
  "refugee_tech_info": "Vi möjligör samarbete mellan alla delar av samhället med målet att tillvarata potentialen hos nyanlända genom effektivt designade och utvecklade lösningar.",
  "setelin_description": "Setelin är resultatet från ett hackathon organiserat av Refugee Tech tillsammans med Migrationsverket och STHLM TECH.
Refugee Tech tog på sig att vidareutveckla plattformen tillsammans med voluntärer.",
  "social_description": " Vänner gör oss till dem vi är, hitta nya vänner och skapa nya bekantskaper",
  "social_title": "Social"
});```

**Comment by miladf** [comment]
THE RIGHT ONE:

$translateProvider.translations("sv", {
  "categories": "kategorier",
  "choose_language": "språk",
  "education_description": "bli mer skicklig, utveckla nya kompetenser och fortsätt växa",
  "education_title": "utbildning",
  "employment_description": "börja nätverka, få ett internship, ett jobb eller starta eget företag",
  "employment_title": "jobb",
  "health_description": "din kropp är ditt tempel. hitta den vård du behöver för att hålla dig frisk",
  "health_title": "hälsa",
  "housing_description": "hitta ett boende i ditt nya hemland.",
  "housing_title": "boende", 
  "information_description": “lär dig allt om Sverige och svenskar, allt från byråkrati till fika",
  "information_title": "information",
  "learnMore":"learn More",
  "interface_direction": "rtl",
  "label": "Svenska",
  "language_description": “Hello! Hola! Här har du några roliga sätt att lära dig nya språk",
  "language_title": "språk",
  "media_comunication_description": "bli inspirerad och ta lärdom från andra människors liv och erfarenheter",
  "media_comunication_title":"media och kommunikation",
  "refugee_tech_info": "Vi möjligör samarbete mellan alla delar av samhället med målet att tillvarata potentialen hos nyanlända genom effektivt designade och utvecklade lösningar.",
  "setelin_description": "Setelin är resultatet från ett hackathon organiserat av Refugee Tech tillsammans med Migrationsverket och STHLM TECH.
Refugee Tech tog på sig att vidareutveckla plattformen tillsammans med voluntärer.",
  "social_description": " vänner gör oss till dem vi är, hitta nya vänner och skapa nya bekantskaper",
  "social_title": "social"
});```
