### ISSUE TITLE
Category view looks like the latest version

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#72]
# Description

The category view  page should be the same as the picture below
# Todo
- Move the text to the correct place
- Change the text as found in the assets
- Change the size of the icon 
- Fix the separator so it is the same
- When an app 'description' is to long, have a "..." in the end (remember that it should only be two rows as in the picture
# No need todo
- Implementing the background of each category is not included in the issue
- Have the 'likes' text or such

Example:
![category- education](https://cloud.githubusercontent.com/assets/1964180/18030007/ab19b812-6ca8-11e6-945c-b5f3b01d54bc.png)
# Assets

Education:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Education.png

Employment:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Employment.png

Healthcare:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+HealthCare.png

Housing:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Housing.png

Information:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Information.png

Language:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Language.png

Medica & Communication:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+MediaCommunication.png

Social
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Social.png

**Comment by miladf** [comment]
Education:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Education.png

Employment:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Employment.png

Healthcare:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+HealthCare.png

Housing:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Housing.png

Information:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Information.png

Language:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Language.png

Medica & Communication:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+MediaCommunication.png
^
Social
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Social.png

**Comment by leosa83** [comment]
@Angamanga Updated description

**Comment by miladf** [comment]
Sketch uses a relative way of defining line-height. But try these and I will get back with the right values if it doesn't seem to look right:
[Category title] = Siri Semibold, size 24 pt, line-height 2.6
[Category description] = Siri Light, size 16 pt, line-height 2.4
[Intiative title] = Siri Semibold, size 14pt, line-height 2.0
[Initiative description] = Siri Light, size 12 pt, line-height 2.0

**Comment by miladf** [comment]
![feedback-achraf-category](https://cloud.githubusercontent.com/assets/1964180/18035639/cf72074e-6d59-11e6-8321-58e68928366c.jpg)
