### ISSUE TITLE
RTL languages break things on mobile

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#78]
# Description

When choosing an RTL language the screen becomes white on safari on iphone.
# Todo
- Debug and fix
- Last resort: change RTL to LTR in interfact direction in the translation objects.

**Comment by miladf** [comment]
@ilix how did you guys do it with Competency? We have some problems when changing the language to Farsi or Arabic on iPhone & Safari :disappointed:

**Comment by miladf** [comment]
@irony can you give tips on what the problem might be as you guys have this in Competency?

**Comment by miladf** [comment]
King @superyass managed to fix this!!
