### ISSUE TITLE
Add a separator between apps in category view

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#81]
# Description

Just add a tiny div separator a couple of pixels height between each item in the list

It should separate each row like in the image:

![slack for ios upload 4](https://cloud.githubusercontent.com/assets/710548/17896185/e5667b24-694f-11e6-9c44-3951ffd2d12f.jpg)

**Comment by leosa83** [comment]
updated the specification

**Comment by leosa83** [comment]
Updated the description of the issue with this image: 

![slack for ios upload 4](https://cloud.githubusercontent.com/assets/710548/17896203/f660cd3a-694f-11e6-9af9-41782d272f66.jpg)

**Comment by miladf** [comment]
You can see the separator in this view:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Housing.png
