### ISSUE TITLE
Make the Setelin footer and Refugeetech footer look good

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#84]
# Description

The Setelin footer and the Refugee Tech footer doesnt look good.

**Comment by miladf** [comment]
Scroll down on this and see how it is:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=MainMenu%3A+Media%2C+education%2C+info%2C+employment%2C+housing%2C+language%2C+health%2C+social+Copy+3.png

**Comment by leosa83** [comment]
@miladf There is no footer in that picture..

**Comment by miladf** [comment]
![footer](https://cloud.githubusercontent.com/assets/1964180/17910564/a5fab8b2-6989-11e6-9543-c77ab9ad2e67.png)

**Comment by leosa83** [comment]
@miladf Ok but thats not a "footer" footer , its  another "category" where the favorites/liked are collected

**Comment by leosa83** [comment]
In other words there is no footer for the app..

**Comment by miladf** [comment]
Haha yeah true. This is the "footer".

**Comment by leosa83** [comment]
So then in fact this is a further implementation of the favorites functionality?

**Comment by leosa83** [comment]
Disregard that , we concluded favorites was not to be implemented but likes should through social plugins..

**Comment by miladf** [comment]
Yes. But I don't know how you will be using facebook likes and social media integration. Lets discuss that first.

**Comment by leosa83** [comment]
:+1:

**Comment by miladf** [comment]
You are fast... :smiley:
