### ISSUE TITLE
New modal for sharing and likes

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#87]
# Description

Clicking the heart icon in detailed app view should open a popup with  these options:
- Add to Setelin favorites
- Facebook Like
- Facebook Share
- Facebook Save
# User interface design

How it should look graphically is to be announced.
# Todo
- Implement the functionality with no regard to how it looks initially
- When there is some type of wireframe ready implement it
# Related Issues

Social plugin #75 
Design #89

**Comment by leosa83** [comment]
@miladf You are responsible for making sure we get a design for this.

**Comment by miladf** [comment]
@leosa83 will not be possible until Sunday then, must check with @Davito163 if he is available on Sunday.
