### ISSUE TITLE
Background images for the category view

### ISSUE THREAD

**Issue by leosa83** [refugeetech/MigHub#90]
# Description

Each category has its own background image as can be seen in the provided assets
# Todo
- Use the background images provided in the assets and load them as the background for each respective category
- Create the folder www/img/category and dump all backgrounds there
# Assets
## Assets for how it should look

Education:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Education.png

Employment:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Employment.png

Healthcare:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+HealthCare.png

Housing:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Housing.png

Information:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Information.png

Language:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Language.png

Medica & Communication:
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+MediaCommunication.png
^
Social
https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AADJJp4PCWFPy7DcMhR828sqa/Preview?dl=0&preview=Category%3A+Social.png
## Assets for the backgrounds (each with three different sizes)

https://www.dropbox.com/sh/ekoyuqi2tkggg6b/AABof5dvR2SJuhAjpUymlV0Ma/BackgroundImages?dl=0

**Comment by miladf** [comment]
Hello @Angamanga, just want to check if you will be available to do this during the weekend or later?

**Comment by Angamanga** [comment]
Hi @miladf! I am planning to do this on monday, am away during the weekend.

**Comment by miladf** [comment]
@Angamanga Coool, thanks for your quick answer :)

**Comment by superyass** [comment]
latest changes made to the category view are in the feature/category2 branch.

**Comment by irony** [comment]
PR Merged.

**Comment by irony** [comment]
Thanks for contribution!

**Comment by superyass** [comment]
your welcome @irony, but the backgrounds are not yet implemented!

**Comment by irony** [comment]
OK, I'll reopen this if there are more work to be done. sorry.

**Comment by superyass** [comment]
no problem, @miladf told me that @Angamanga will implement the backgrounds...

**Comment by Angamanga** [comment]
Hi @superyass and @irony! Did I miss something? Are there more work to be done on this issue?

**Comment by superyass** [comment]
actually now we just need to merge this PR #99
